version: 2.1


jobs:
  build:
    machine:
      resource_class: gpu.nvidia.small
    executor: python/default
    steps:
      - checkout
      - run: 
          name: Display Python version
          command: python -c "import sys; print(sys.version)"

