version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    executor: python/default
    steps:
      - checkout
      - run: nvidia-smi
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
      - run: 
          name: Display Python version
          command: python -c "import sys; print(sys.version)"


workflows:
  main:
    jobs:
      - build-and-test
